// 英雄联盟全英雄数据
// lanes: 参考 OPGG/U.GG 实际分路出场数据（2025赛季Meta）
// 使用 Riot Data Dragon CDN 加载头像
const DDRAGON = 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/';

const champions = [
  { id: 'Aatrox', name: '暗裔剑魔', en: 'Aatrox', title: '亚托克斯', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Ahri', name: '九尾妖狐', en: 'Ahri', title: '阿狸', roles: ['mage','assassin'], lanes: ['mid'] },
  { id: 'Akali', name: '离群之刺', en: 'Akali', title: '阿卡丽', roles: ['assassin'], lanes: ['mid','top'] },
  { id: 'Akshan', name: '豪勇哨兵', en: 'Akshan', title: '阿克尚', roles: ['marksman','assassin'], lanes: ['mid','top'] },
  { id: 'Alistar', name: '牛头酋长', en: 'Alistar', title: '阿利斯塔', roles: ['tank','support'], lanes: ['support'] },
  { id: 'Amumu', name: '殇之木乃伊', en: 'Amumu', title: '阿木木', roles: ['tank','mage'], lanes: ['jungle','support'] },
  { id: 'Anivia', name: '冰晶凤凰', en: 'Anivia', title: '艾尼维亚', roles: ['mage'], lanes: ['mid'] },
  { id: 'Annie', name: '黑暗之女', en: 'Annie', title: '安妮', roles: ['mage'], lanes: ['mid','support'] },
  { id: 'Aphelios', name: '残月之肃', en: 'Aphelios', title: '厄斐琉斯', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Ashe', name: '寒冰射手', en: 'Ashe', title: '艾希', roles: ['marksman','support'], lanes: ['adc','support'] },
  { id: 'AurelionSol', name: '铸星龙王', en: 'Aurelion Sol', title: '奥瑞利安·索尔', roles: ['mage'], lanes: ['mid'] },
  { id: 'Aurora', name: '女巫猎手', en: 'Aurora', title: '欧若拉', roles: ['mage','assassin'], lanes: ['mid','top'] },
  { id: 'Azir', name: '沙漠皇帝', en: 'Azir', title: '阿兹尔', roles: ['mage'], lanes: ['mid'] },
  { id: 'Bard', name: '星界游神', en: 'Bard', title: '巴德', roles: ['support','mage'], lanes: ['support'] },
  { id: 'BelVeth', name: '虚空女皇', en: "Bel'Veth", title: '卑尔维斯', roles: ['fighter'], lanes: ['jungle'] },
  { id: 'Blitzcrank', name: '蒸汽机器人', en: 'Blitzcrank', title: '布里茨', roles: ['tank','support'], lanes: ['support'] },
  { id: 'Brand', name: '复仇焰魂', en: 'Brand', title: '布兰德', roles: ['mage'], lanes: ['support','mid'] },
  { id: 'Braum', name: '弗雷尔卓德之心', en: 'Braum', title: '布隆', roles: ['support','tank'], lanes: ['support'] },
  { id: 'Briar', name: '嗜血猎手', en: 'Briar', title: '布莱尔', roles: ['fighter','assassin'], lanes: ['jungle'] },
  { id: 'Caitlyn', name: '皮城女警', en: 'Caitlyn', title: '凯特琳', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Camille', name: '青钢影', en: 'Camille', title: '卡蜜尔', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Cassiopeia', name: '魔蛇之拥', en: 'Cassiopeia', title: '卡西奥佩娅', roles: ['mage'], lanes: ['mid'] },
  { id: 'Chogath', name: '虚空恐惧', en: "Cho'Gath", title: '科加斯', roles: ['tank','mage'], lanes: ['top'] },
  { id: 'Corki', name: '英勇投弹手', en: 'Corki', title: '库奇', roles: ['marksman','mage'], lanes: ['mid'] },
  { id: 'Darius', name: '诺克萨斯之手', en: 'Darius', title: '德莱厄斯', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Diana', name: '皎月女神', en: 'Diana', title: '戴安娜', roles: ['fighter','assassin'], lanes: ['jungle','mid'] },
  { id: 'Draven', name: '荣耀行刑官', en: 'Draven', title: '德莱文', roles: ['marksman'], lanes: ['adc'] },
  { id: 'DrMundo', name: '祖安狂人', en: 'Dr. Mundo', title: '蒙多', roles: ['fighter','tank'], lanes: ['top','jungle'] },
  { id: 'Ekko', name: '时间刺客', en: 'Ekko', title: '艾克', roles: ['assassin','fighter'], lanes: ['jungle','mid'] },
  { id: 'Elise', name: '蜘蛛女皇', en: 'Elise', title: '伊莉丝', roles: ['mage','fighter'], lanes: ['jungle'] },
  { id: 'Evelynn', name: '痛苦之拥', en: 'Evelynn', title: '伊芙琳', roles: ['assassin','mage'], lanes: ['jungle'] },
  { id: 'Ezreal', name: '探险家', en: 'Ezreal', title: '伊泽瑞尔', roles: ['marksman','mage'], lanes: ['adc'] },
  { id: 'Fiddlesticks', name: '远古恐惧', en: 'Fiddlesticks', title: '费德提克', roles: ['mage','support'], lanes: ['jungle','support'] },
  { id: 'Fiora', name: '无双剑姬', en: 'Fiora', title: '菲奥娜', roles: ['fighter','assassin'], lanes: ['top'] },
  { id: 'Fizz', name: '潮汐海灵', en: 'Fizz', title: '菲兹', roles: ['assassin','fighter'], lanes: ['mid'] },
  { id: 'Galio', name: '正义巨像', en: 'Galio', title: '加里奥', roles: ['tank','mage'], lanes: ['mid','support'] },
  { id: 'Gangplank', name: '海洋之灾', en: 'Gangplank', title: '普朗克', roles: ['fighter'], lanes: ['top','mid'] },
  { id: 'Garen', name: '德玛西亚之力', en: 'Garen', title: '盖伦', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Gnar', name: '迷失之牙', en: 'Gnar', title: '纳尔', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Gragas', name: '酒桶', en: 'Gragas', title: '古拉加斯', roles: ['fighter','mage'], lanes: ['jungle','top','mid'] },
  { id: 'Graves', name: '法外狂徒', en: 'Graves', title: '格雷福斯', roles: ['marksman'], lanes: ['jungle'] },
  { id: 'Gwen', name: '裁缝师', en: 'Gwen', title: '格温', roles: ['fighter','assassin'], lanes: ['top'] },
  { id: 'Hecarim', name: '战争之影', en: 'Hecarim', title: '赫卡里姆', roles: ['fighter','tank'], lanes: ['jungle'] },
  { id: 'Heimerdinger', name: '大发明家', en: 'Heimerdinger', title: '黑默丁格', roles: ['mage'], lanes: ['mid','top','support'] },
  { id: 'Hwei', name: '画师', en: 'Hwei', title: '彗', roles: ['mage','support'], lanes: ['mid','support'] },
  { id: 'Illaoi', name: '海兽祭司', en: 'Illaoi', title: '俄洛伊', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Irelia', name: '刀锋舞者', en: 'Irelia', title: '艾瑞莉娅', roles: ['fighter','assassin'], lanes: ['top','mid'] },
  { id: 'Ivern', name: '翠神', en: 'Ivern', title: '艾翁', roles: ['support','mage'], lanes: ['jungle'] },
  { id: 'Janna', name: '风暴之怒', en: 'Janna', title: '迦娜', roles: ['support','mage'], lanes: ['support'] },
  { id: 'JarvanIV', name: '德玛西亚皇子', en: 'Jarvan IV', title: '嘉文四世', roles: ['tank','fighter'], lanes: ['jungle'] },
  { id: 'Jax', name: '武器大师', en: 'Jax', title: '贾克斯', roles: ['fighter','assassin'], lanes: ['top','jungle'] },
  { id: 'Jayce', name: '未来守护者', en: 'Jayce', title: '杰斯', roles: ['fighter','marksman'], lanes: ['top','mid'] },
  { id: 'Jhin', name: '戏命师', en: 'Jhin', title: '烬', roles: ['marksman','mage'], lanes: ['adc'] },
  { id: 'Jinx', name: '暴走萝莉', en: 'Jinx', title: '金克丝', roles: ['marksman'], lanes: ['adc'] },
  { id: 'KSante', name: '破败之主', en: "K'Sante", title: '奎桑提', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Kaisa', name: '虚空之女', en: "Kai'Sa", title: '卡莎', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Kalista', name: '复仇之矛', en: 'Kalista', title: '卡莉丝塔', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Karma', name: '天启者', en: 'Karma', title: '卡尔玛', roles: ['mage','support'], lanes: ['support','mid'] },
  { id: 'Karthus', name: '死亡颂唱者', en: 'Karthus', title: '卡尔萨斯', roles: ['mage'], lanes: ['jungle','mid'] },
  { id: 'Kassadin', name: '虚空行者', en: 'Kassadin', title: '卡萨丁', roles: ['assassin','mage'], lanes: ['mid'] },
  { id: 'Katarina', name: '不祥之刃', en: 'Katarina', title: '卡特琳娜', roles: ['assassin','mage'], lanes: ['mid'] },
  { id: 'Kayle', name: '正义天使', en: 'Kayle', title: '凯尔', roles: ['fighter','mage'], lanes: ['top'] },
  { id: 'Kayn', name: '影流之镰', en: 'Kayn', title: '凯隐', roles: ['fighter','assassin'], lanes: ['jungle'] },
  { id: 'Kennen', name: '狂暴之心', en: 'Kennen', title: '凯南', roles: ['mage','marksman'], lanes: ['top'] },
  { id: 'Khazix', name: '虚空掠夺者', en: "Kha'Zix", title: '卡兹克', roles: ['assassin'], lanes: ['jungle'] },
  { id: 'Kindred', name: '永猎双子', en: 'Kindred', title: '千珏', roles: ['marksman'], lanes: ['jungle'] },
  { id: 'Kled', name: '暴怒骑士', en: 'Kled', title: '克烈', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'KogMaw', name: '深渊巨口', en: "Kog'Maw", title: '克格莫', roles: ['marksman','mage'], lanes: ['adc'] },
  { id: 'Leblanc', name: '诡术妖姬', en: 'LeBlanc', title: '乐芙兰', roles: ['assassin','mage'], lanes: ['mid'] },
  { id: 'LeeSin', name: '盲僧', en: 'Lee Sin', title: '李青', roles: ['fighter','assassin'], lanes: ['jungle'] },
  { id: 'Leona', name: '曙光女神', en: 'Leona', title: '蕾欧娜', roles: ['tank','support'], lanes: ['support'] },
  { id: 'Lillia', name: '腼腆绽放', en: 'Lillia', title: '莉莉娅', roles: ['fighter','mage'], lanes: ['jungle'] },
  { id: 'Lissandra', name: '冰霜女巫', en: 'Lissandra', title: '丽桑卓', roles: ['mage'], lanes: ['mid'] },
  { id: 'Lucian', name: '圣枪游侠', en: 'Lucian', title: '卢锡安', roles: ['marksman'], lanes: ['adc','mid'] },
  { id: 'Lulu', name: '仙灵女巫', en: 'Lulu', title: '璐璐', roles: ['support','mage'], lanes: ['support'] },
  { id: 'Lux', name: '光辉女郎', en: 'Lux', title: '拉克丝', roles: ['mage','support'], lanes: ['support','mid'] },
  { id: 'Malphite', name: '熔岩巨兽', en: 'Malphite', title: '墨菲特', roles: ['tank','fighter'], lanes: ['top','support'] },
  { id: 'Malzahar', name: '虚空先知', en: 'Malzahar', title: '玛尔扎哈', roles: ['mage','assassin'], lanes: ['mid'] },
  { id: 'Maokai', name: '扭曲树精', en: 'Maokai', title: '茂凯', roles: ['tank','mage'], lanes: ['support','jungle','top'] },
  { id: 'MasterYi', name: '无极剑圣', en: 'Master Yi', title: '易大师', roles: ['assassin','fighter'], lanes: ['jungle'] },
  { id: 'Milio', name: '温焰守护', en: 'Milio', title: '米利欧', roles: ['support'], lanes: ['support'] },
  { id: 'MissFortune', name: '赏金猎人', en: 'Miss Fortune', title: '好运姐', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Mordekaiser', name: '铁铠冥魂', en: 'Mordekaiser', title: '莫德凯撒', roles: ['fighter'], lanes: ['top'] },
  { id: 'Morgana', name: '堕落天使', en: 'Morgana', title: '莫甘娜', roles: ['mage','support'], lanes: ['support','mid'] },
  { id: 'Naafiri', name: '猎犬之首', en: 'Naafiri', title: '纳菲利', roles: ['assassin'], lanes: ['mid'] },
  { id: 'Nami', name: '唤潮鲛姬', en: 'Nami', title: '娜美', roles: ['support','mage'], lanes: ['support'] },
  { id: 'Nasus', name: '沙漠死神', en: 'Nasus', title: '内瑟斯', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Nautilus', name: '深海泰坦', en: 'Nautilus', title: '诺提勒斯', roles: ['tank','support'], lanes: ['support'] },
  { id: 'Neeko', name: '万花通灵', en: 'Neeko', title: '妮蔻', roles: ['mage','support'], lanes: ['mid','support'] },
  { id: 'Nidalee', name: '狂野女猎手', en: 'Nidalee', title: '奈德丽', roles: ['assassin'], lanes: ['jungle'] },
  { id: 'Nilah', name: '欢愉之拥', en: 'Nilah', title: '尼菈', roles: ['fighter','marksman'], lanes: ['adc'] },
  { id: 'Nocturne', name: '永恒梦魇', en: 'Nocturne', title: '魔腾', roles: ['assassin','fighter'], lanes: ['jungle'] },
  { id: 'Nunu', name: '雪原双子', en: 'Nunu & Willump', title: '努努和威朗普', roles: ['tank','fighter'], lanes: ['jungle'] },
  { id: 'Olaf', name: '狂战士', en: 'Olaf', title: '奥拉夫', roles: ['fighter','tank'], lanes: ['top','jungle'] },
  { id: 'Orianna', name: '发条魔灵', en: 'Orianna', title: '奥莉安娜', roles: ['mage','support'], lanes: ['mid'] },
  { id: 'Ornn', name: '山隐之焰', en: 'Ornn', title: '奥恩', roles: ['tank','fighter'], lanes: ['top'] },
  { id: 'Pantheon', name: '不屈之枪', en: 'Pantheon', title: '潘森', roles: ['fighter','assassin'], lanes: ['support','mid','top'] },
  { id: 'Poppy', name: '圣锤之毅', en: 'Poppy', title: '波比', roles: ['tank','fighter'], lanes: ['top','jungle','support'] },
  { id: 'Pyke', name: '血港鬼影', en: 'Pyke', title: '派克', roles: ['support','assassin'], lanes: ['support'] },
  { id: 'Qiyana', name: '元素女皇', en: 'Qiyana', title: '奇亚娜', roles: ['assassin','fighter'], lanes: ['mid'] },
  { id: 'Quinn', name: '德玛西亚之翼', en: 'Quinn', title: '奎因', roles: ['marksman','assassin'], lanes: ['top'] },
  { id: 'Rakan', name: '幻翎', en: 'Rakan', title: '洛', roles: ['support'], lanes: ['support'] },
  { id: 'Rammus', name: '披甲龙龟', en: 'Rammus', title: '拉莫斯', roles: ['tank','fighter'], lanes: ['jungle'] },
  { id: 'RekSai', name: '虚空遁地兽', en: "Rek'Sai", title: '雷克塞', roles: ['fighter'], lanes: ['jungle'] },
  { id: 'Rell', name: '铁骑冲锋', en: 'Rell', title: '锐尔', roles: ['tank','support'], lanes: ['support'] },
  { id: 'Renata', name: '裂缝男爵夫人', en: 'Renata Glasc', title: '烈娜塔', roles: ['support','mage'], lanes: ['support'] },
  { id: 'Renekton', name: '荒漠屠夫', en: 'Renekton', title: '雷克顿', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Rengar', name: '傲之追猎者', en: 'Rengar', title: '雷恩加尔', roles: ['assassin','fighter'], lanes: ['jungle','top'] },
  { id: 'Riven', name: '放逐之刃', en: 'Riven', title: '锐雯', roles: ['fighter','assassin'], lanes: ['top'] },
  { id: 'Rumble', name: '机械公敌', en: 'Rumble', title: '兰博', roles: ['fighter','mage'], lanes: ['top','mid'] },
  { id: 'Ryze', name: '符文法师', en: 'Ryze', title: '瑞兹', roles: ['mage','fighter'], lanes: ['mid','top'] },
  { id: 'Samira', name: '沙漠玫瑰', en: 'Samira', title: '莎弥拉', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Sejuani', name: '凛冬之怒', en: 'Sejuani', title: '瑟庄妮', roles: ['tank','fighter'], lanes: ['jungle'] },
  { id: 'Senna', name: '愁予哨兵', en: 'Senna', title: '赛娜', roles: ['marksman','support'], lanes: ['support','adc'] },
  { id: 'Seraphine', name: '星籁歌姬', en: 'Seraphine', title: '萨勒芬妮', roles: ['support','mage'], lanes: ['support','adc'] },
  { id: 'Sett', name: '腕豪', en: 'Sett', title: '瑟提', roles: ['fighter','tank'], lanes: ['top','support'] },
  { id: 'Shaco', name: '恶魔小丑', en: 'Shaco', title: '萨科', roles: ['assassin'], lanes: ['jungle','support'] },
  { id: 'Shen', name: '暮光之眼', en: 'Shen', title: '慎', roles: ['tank'], lanes: ['top','support'] },
  { id: 'Shyvana', name: '龙血武姬', en: 'Shyvana', title: '希瓦娜', roles: ['fighter','tank'], lanes: ['jungle'] },
  { id: 'Singed', name: '炼金术士', en: 'Singed', title: '辛吉德', roles: ['tank','fighter'], lanes: ['top'] },
  { id: 'Sion', name: '亡灵战神', en: 'Sion', title: '赛恩', roles: ['tank','fighter'], lanes: ['top'] },
  { id: 'Sivir', name: '战争女神', en: 'Sivir', title: '希维尔', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Skarner', name: '水晶先锋', en: 'Skarner', title: '斯卡纳', roles: ['fighter','tank'], lanes: ['jungle'] },
  { id: 'Smolder', name: '焰灵小龙', en: 'Smolder', title: '斯莫德', roles: ['marksman','mage'], lanes: ['adc','mid'] },
  { id: 'Sona', name: '琴瑟仙女', en: 'Sona', title: '娑娜', roles: ['support','mage'], lanes: ['support'] },
  { id: 'Soraka', name: '众星之子', en: 'Soraka', title: '索拉卡', roles: ['support','mage'], lanes: ['support'] },
  { id: 'Swain', name: '策士统领', en: 'Swain', title: '斯维因', roles: ['mage','fighter'], lanes: ['support','mid','adc'] },
  { id: 'Sylas', name: '解脱者', en: 'Sylas', title: '塞拉斯', roles: ['mage','assassin'], lanes: ['mid','jungle'] },
  { id: 'Syndra', name: '暗黑元首', en: 'Syndra', title: '辛德拉', roles: ['mage'], lanes: ['mid'] },
  { id: 'TahmKench', name: '河流之王', en: 'Tahm Kench', title: '塔姆', roles: ['support','tank'], lanes: ['top','support'] },
  { id: 'Taliyah', name: '岩雀', en: 'Taliyah', title: '塔莉垭', roles: ['mage'], lanes: ['jungle','mid'] },
  { id: 'Talon', name: '刀锋之影', en: 'Talon', title: '泰隆', roles: ['assassin'], lanes: ['mid','jungle'] },
  { id: 'Taric', name: '宝石骑士', en: 'Taric', title: '塔里克', roles: ['support','fighter'], lanes: ['support'] },
  { id: 'Teemo', name: '迅捷斥候', en: 'Teemo', title: '提莫', roles: ['marksman','mage'], lanes: ['top'] },
  { id: 'Thresh', name: '魂锁典狱长', en: 'Thresh', title: '锤石', roles: ['support','fighter'], lanes: ['support'] },
  { id: 'Tristana', name: '麦林炮手', en: 'Tristana', title: '崔丝塔娜', roles: ['marksman','assassin'], lanes: ['adc','mid'] },
  { id: 'Trundle', name: '巨魔之王', en: 'Trundle', title: '特朗德尔', roles: ['fighter','tank'], lanes: ['top','jungle'] },
  { id: 'Tryndamere', name: '蛮族之王', en: 'Tryndamere', title: '泰达米尔', roles: ['fighter','assassin'], lanes: ['top'] },
  { id: 'TwistedFate', name: '卡牌大师', en: 'Twisted Fate', title: '崔斯特', roles: ['mage'], lanes: ['mid'] },
  { id: 'Twitch', name: '瘟疫之源', en: 'Twitch', title: '图奇', roles: ['marksman','assassin'], lanes: ['adc','support'] },
  { id: 'Udyr', name: '灵魂行者', en: 'Udyr', title: '乌迪尔', roles: ['fighter','tank'], lanes: ['jungle','top'] },
  { id: 'Urgot', name: '无畏战车', en: 'Urgot', title: '厄加特', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Varus', name: '惩戒之箭', en: 'Varus', title: '韦鲁斯', roles: ['marksman','mage'], lanes: ['adc','mid'] },
  { id: 'Vayne', name: '暗夜猎手', en: 'Vayne', title: '薇恩', roles: ['marksman','assassin'], lanes: ['adc','top'] },
  { id: 'Veigar', name: '邪恶小法师', en: 'Veigar', title: '维迦', roles: ['mage'], lanes: ['mid','adc'] },
  { id: 'Velkoz', name: '虚空之眼', en: "Vel'Koz", title: '维克兹', roles: ['mage'], lanes: ['mid','support'] },
  { id: 'Vex', name: '愁云使者', en: 'Vex', title: '薇古丝', roles: ['mage'], lanes: ['mid'] },
  { id: 'Vi', name: '皮城执法官', en: 'Vi', title: '蔚', roles: ['fighter','assassin'], lanes: ['jungle'] },
  { id: 'Viego', name: '破败之王', en: 'Viego', title: '佛耶戈', roles: ['assassin','fighter'], lanes: ['jungle'] },
  { id: 'Viktor', name: '机械先驱', en: 'Viktor', title: '维克托', roles: ['mage'], lanes: ['mid'] },
  { id: 'Vladimir', name: '猩红收割者', en: 'Vladimir', title: '弗拉基米尔', roles: ['mage'], lanes: ['mid','top'] },
  { id: 'Volibear', name: '雷霆咆哮', en: 'Volibear', title: '沃利贝尔', roles: ['fighter','tank'], lanes: ['top','jungle'] },
  { id: 'Warwick', name: '祖安怒兽', en: 'Warwick', title: '沃里克', roles: ['fighter','tank'], lanes: ['jungle','top'] },
  { id: 'Wukong', name: '齐天大圣', en: 'Wukong', title: '悟空', roles: ['fighter','tank'], lanes: ['jungle','top'] },
  { id: 'Xayah', name: '逆羽', en: 'Xayah', title: '霞', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Xerath', name: '远古巫灵', en: 'Xerath', title: '泽拉斯', roles: ['mage'], lanes: ['mid','support'] },
  { id: 'XinZhao', name: '德邦总管', en: 'Xin Zhao', title: '赵信', roles: ['fighter','assassin'], lanes: ['jungle'] },
  { id: 'Yasuo', name: '疾风剑豪', en: 'Yasuo', title: '亚索', roles: ['fighter','assassin'], lanes: ['mid','top','adc'] },
  { id: 'Yone', name: '封魔剑魂', en: 'Yone', title: '永恩', roles: ['fighter','assassin'], lanes: ['mid','top'] },
  { id: 'Yorick', name: '牧魂人', en: 'Yorick', title: '约里克', roles: ['fighter','tank'], lanes: ['top'] },
  { id: 'Yuumi', name: '魔法猫咪', en: 'Yuumi', title: '悠米', roles: ['support','mage'], lanes: ['support'] },
  { id: 'Zac', name: '生化魔人', en: 'Zac', title: '扎克', roles: ['tank','fighter'], lanes: ['jungle','top'] },
  { id: 'Zed', name: '影流之主', en: 'Zed', title: '劫', roles: ['assassin'], lanes: ['mid'] },
  { id: 'Zeri', name: '放电少女', en: 'Zeri', title: '泽丽', roles: ['marksman'], lanes: ['adc'] },
  { id: 'Ziggs', name: '爆破鬼才', en: 'Ziggs', title: '吉格斯', roles: ['mage'], lanes: ['mid','adc'] },
  { id: 'Zilean', name: '时光守护者', en: 'Zilean', title: '基兰', roles: ['support','mage'], lanes: ['support','mid'] },
  { id: 'Zoe', name: '暮光星灵', en: 'Zoe', title: '佐伊', roles: ['mage'], lanes: ['mid'] },
  { id: 'Zyra', name: '荆棘之兴', en: 'Zyra', title: '婕拉', roles: ['mage','support'], lanes: ['support'] },
];

function getChampionImg(id) {
    return DDRAGON + id + '.png';
}

const roleNames = {
    fighter: '战士',
    tank: '坦克',
    mage: '法师',
    assassin: '刺客',
    marksman: '射手',
    support: '辅助',
};

const roleColors = {
    fighter: '#c89b3c',
    tank: '#3d9be9',
    mage: '#9b59b6',
    assassin: '#e74c3c',
    marksman: '#2ecc71',
    support: '#1abc9c',
};
